### ISSUE TITLE
config.js does not work

### ISSUE THREAD

**Issue by xverges** [swyphcosmo/endomondo-js#1]
I suspect that `config.js.example` does not reflect the structure of your real `config.js`. 

I changed it to JSON and renamed it `config.json`. Or I could have changed `config.js` to export the credentials.

Thanks for your script!

**Comment by swyphcosmo** [comment]
Thanks for catching this. I thought I had already pushed a fix. My intention was to have `config.js` export the credentials.  Fixed it here: 6cd3fdd5a751142ea882693bc8cf70864dc8ddae
